name: Hello + Cache Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 23ds2000079@ds.study.iitm.ac.in
        run: echo "Hello, world! from 23ds2000079@ds.study.iitm.ac.in"

  cache-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prime-cache-ef5e34e
        id: prime_cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: cache-ef5e34e

      - name: Show cache result
        run: echo "Cache hit? ${{ steps.prime_cache.outputs.cache-hit }}"
