name: Dependency Cache Prime

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Prime dependency cache
      - name: Prime cache
        id: prime-cache-ef5e34e   # <-- this is required to reference outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: cache-ef5e34e

      # Step 3: Echo cache hit/miss
      - name: Show cache result
        run: echo "Cache hit? ${{ steps.prime-cache-ef5e34e.outputs.cache-hit }}"
